# Generated by Django 5.1.3 on 2024-11-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="time_update",
        ),
    ]
